MyKitchenHelper/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', 'MyKitchenHelper.views.home', name='home'),
    url(r'^inventory/', include('items.urls', namespace="inventory")),
    url(r'^recipes/', include('recipes.urls', namespace="recipes")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}),
]

inventory/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # Examples:
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add')
]

recipes/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^regroup$', views.regroup, name='regroup'),
    url(r'^new/$', views.new, name='new'),
    url(r'^edit/$', views.edit, name='edit')
]

items/models.py
from django.db import models
from django.db.models.fields import CharField

class LowercaseCharField(CharField):
	def get_db_prep_value(self, value, connection, prepared=False):
		return value.lower()

class ItemCategory(models.Model):
	name = LowercaseCharField(max_length=50, unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "item category"
		verbose_name_plural = "item categories"
		ordering = ['name']
			

class Item(models.Model):
	name = LowercaseCharField(max_length=50, unique=True)
	category = models.ForeignKey(ItemCategory)
	stock = models.PositiveSmallIntegerField(default="1")
	tracked = models.BooleanField(default=0)
	threshold = models.PositiveSmallIntegerField(default="0")

	def first_letter(self):
		return self.name and self.name[0] or ''

	def status(self):
		if not self.tracked:
			return {"status":"na", 	"order":3}
		elif self.stock == 0:
			return {"status":"out", "order":0}
		elif self.stock >= self.threshold:
			return {"status":"ok", 	"order":2}
		else:
			return {"status":"low", "order":1}

	class Meta:
		ordering = ['name']

	def __str__(self):
		return self.name

recipes/models.py
from django.db import models
from django.db.models.fields import CharField

class LowercaseCharField(CharField):
	def get_db_prep_value(self, value, connection, prepared=False):
		return value.lower()

class Recipe(models.Model):
	name = LowercaseCharField(max_length=50, unique=True)

	def first_letter(self):
		return self.name and self.name[0] or ''

	class Meta:
		ordering = ['name']

	def __str__(self):
		return self.name

items/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):

	class Meta:
		model = Item
		fields = ('name', 'category', 'stock', 'tracked', 'threshold')

recipes/forms.py
from django import forms
from .models import Recipe

class RecipeForm(forms.ModelForm):

	class Meta:
		model = Recipe
		fields = ('name',)

MyKitchenHelper/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
	return render(request, 'MyKitchenHelper/home.html', {})

items/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, render_to_response
from django.views.generic import ListView, DetailView, CreateView
from django.forms.models import modelformset_factory
from .models import Item
from .forms import ItemForm

@login_required
def index(request):
	items = Item.objects.all()
	groupby = "name"
	return render(request, 
				  "inventory/index.html", 
				  {'items': items, 'groupby': groupby})

@login_required
def regroup(request):
	items = Item.objects.all()
	groupby = request.GET.get("groupby")
	return render_to_response("inventory/index_results.html", 
							  {'items': items, 'groupby': groupby})


@login_required
def new(request):
	items = Item.objects.all()
	groupby = "name"
	if request.method == "POST":
		form = ItemForm(request.POST)
		if form.is_valid():
			form.save()
			form = ItemForm()
	else:
		form = ItemForm()
	return render(request, 
				  "inventory/new.html", 
				  {'items': items, 'groupby': groupby, 'form': form})

@login_required
def edit(request):
	ItemFormSet = modelformset_factory(
		Item, 
		fields=('name', 'category', 'stock', 'tracked', 'threshold'),
		extra=0
	)
	if request.method == "POST":
		formset = ItemFormSet(request.POST, request.FILES)
		if formset.is_valid():
			formset.save()
			return redirect("inventory:index")
	else:
		formset = ItemFormSet()
	return render(request, "inventory/edit.html", {"formset": formset})

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Recipe
from .forms import RecipeForm

@login_required
def index(request):
	recipes = Recipe.objects.all()
	groupby = "name"
	return render(request, 
				  "recipes/index.html", 
				  {'recipes': recipes, 'groupby': groupby})

@login_required
def regroup(request):
	recipes = Recipe.objects.all()
	groupby = request.GET.get("groupby")
	return render_to_response("recipes/index_results.html", 
							  {'recipes': recipes, 'groupby': groupby})


@login_required
def new(request):
	recipes = Recipe.objects.all()
	groupby = "name"
	if request.method == "POST":
		form = RecipeForm(request.POST)
		if form.is_valid():
			form.save()
			form = RecipeForm()
	else:
		form = RecipeForm()
	return render(request, 
				  "recipes/new.html", 
				  {'recipes': recipes, 'groupby': groupby, 'form': form})

@login_required
def edit(request):
	return render(request, 
				  "recipes/edit.html", 
				  {})

MyKitchenHelper/templates/MyKitchenHelper/base.html
<!DOCTYPE html>
<html>
<head>

	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- JQUERY -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

	<!-- Google Fonts for Web Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Mystery+Quest' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oregano' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Khula:300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>

	<!-- Font Awesome For Font Icons -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>

	{% block csslink %}{% endblock %}

	<title>My Kitchen Helper</title>
</head>

<body>

	<header id="apptitle">My Kitchen Helper</header>
	<i id="mainmenu" class="fa fa-bars"></i>

	<nav id="mainnav">
		<ul>
			<li>
				<a id="homeNav" href="{% url 'home' %}">
					<i class="fa fa-home"></i><span>Home</span>
				</a>
			</li>
			<li>
				<a id="inventoryNav" href="{% url 'inventory:index' %}">
					<i class="fa fa-inbox"></i><span>Inventory</span>
				</a>
			</li>
			<li>
				<a id="recipesNav" href="{% url 'recipes:index' %}">
					<i class="fa fa-book"></i><span>Recipe Book</span>
				</a>
			</li>
			<li>
				<a href="">
					<i class="fa fa-calendar"></i><span>Meal Plan</span>
				</a>
			</li>
			<li>
				<a href="">
					<i class="fa fa-shopping-cart"></i><span>Shopping</span>
				</a>
			</li>
			<li>
				<a href="/admin">
					<i class="fa fa-database"></i><span>Administration</span>
				</a>
			</li>
		</ul>
	</nav>

	<section id="main">
	
		<header id="contenttitle">
			{% block title %}{% endblock %}
		</header>
	
		<nav id="contentnav">
			{% block nav %}{% endblock %}
		</nav>

		<section id="precontent">
			{% block precontent %}{% endblock %}
		</section>
	
		<section id="content">
			{% block content %}{% endblock %}
		</section>
	
		<footer> </footer>
	
	</section>

	<script src="{% static "scripts/main.js" %}"></script>
	{% block scriptlink %}{% endblock %}

</body>
</html>

MyKitchenHelper/templates/MyKitchenHelper/base_index.html
{% extends 'MyKitchenHelper/base.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href={% block appcss %}{% endblock %}/>
{% endblock %}

<!-- TITLE -->
{% block title %}{% endblock %}

<!-- NAV -->
{% block nav %}
{% endblock %}

{% block content %}
	<div id="objectlist">
		{% block objectlist %}{% endblock %}
	</div>
{% endblock %}

{% block scriptlink %}
<script>
	activeNav({% block activenav %}{% endblock %});
	var index_url = {% block indexurl %}{% endblock %}
</script>
<script src="{% static "scripts/secondary.js" %}"></script>
<script>
	attachGroupDisplayEventHandler()
</script>

{% endblock %}

MyKitchenHelper/templates/MyKitchenHelper/base_main.html
{% extends 'MyKitchenHelper/base.html' %}

{% block main %}

<header id="contenttitle">{% block title %}{% endblock %}</header>
<nav>
	{% block nav %}{% endblock %}
</nav>
<section id="content">
	{% block content %}{% endblock %}
</section>
<footer> </footer>
{% endblock %}

MyKitchenHelper/templates/MyKitchenHelper/home.html
{% extends 'MyKitchenHelper/base.html' %}

{% block title %}
{% if user.is_authenticated %}
Welcome, {{ user.username }}!
{% else %}
Log In
{% endif %}
{% endblock %}

{% block content %}
<a href="{% url 'django.contrib.auth.views.logout' %}">Log out</a>
{% endblock %}

{% block scriptlink %}
<script>
	activeNav("homeNav");
</script>
{% endblock %}

inventory/templates/inventory/index.html
{% extends 'MyKitchenHelper/base_main.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/inventory.css" %}"/>
{% endblock %}

<!-- TITLE -->

{% block title %}Inventory{% endblock %}

<!-- NAV BUTTONS -->

{% block nav %}
<ul>
	<li id="groupby">
		<label>Group by: </label>
		<select id="InventoryGroupBy" autocomplete="off">
			<option value="name" selected="selected">name</option>
			<option value="category">category</option>
			<option value="status">status</option>
		</select>
	</li>
	<li id="additem"><i class="fa fa-plus-square"></i></li>
	<li id="edititems"><i class="fa fa-pencil-square"></i></li>
</ul>
{% endblock %}

{% block content %}
<div id="adddiv">
	{% include "inventory/index_adddiv.html" %}
</div>

<div id="inventorylist">
	{% include "inventory/index_results.html" %}
</div>
{% endblock %}


<!-- JS -->

{% block scriptlink %}
<script>
	activeNav("inventoryNav");
	var index_url = "{% url 'inventory:index' %}"
	var add_url = "{% url 'inventory:add' %}"
</script>
<script src="{% static "scripts/inventory.js" %}"></script>
<script>
attachGroupDisplayEventHandler()
updateAddDiv()
</script>
{% endblock %}

inventory/templates/inventory/index_results.html
{% if groupby == "name" %}
	{% regroup items by first_letter as grouped_list %}
{% elif groupby == "category" %}
	{% regroup items|dictsort:"item.category.name" by item.category as grouped_list %}
{% elif groupby == "status" %}
	{% regroup items|dictsort:"status.order" by status.status as grouped_list %}
{% endif %}

{% for group in grouped_list %}
<table class="group">
	<colgroup>
		<col span="1"></col>
		<col span="1"></col>
		<col span="1"></col>
	</colgroup>
	<tr class="grouphead">
		<th>
			<i class="groupdisplay fa fa-toggle-up"></i>
			{{ group.grouper|upper }}</th>
		<th>stock</th>
		<th>status</th>
		<th></th>
	</tr>
	{% for item in group.list %}
	<tr class="datarow rowshow">
		<td>{{ item }}</td>
		<td>{{ item.stock }}</td>
		<td>
		{% if item.status.status = "out" %}
		<i class="fa fa-times-circle"></i>
		{% elif item.status.status = "low" %}
		<i class="fa fa-exclamation-circle"></i>
		{% elif item.status.status = "na" %}
		<i class="fa fa-question-circle"></i>
		{% elif item.status.status = "ok" %}
		<i class="fa fa-check-circle"></i>
		{% endif %}
		</td>
		<td></td>
	</tr>
	{% endfor %}
</table>

{% endfor %}

items/templates/inventory/base.html
{% extends 'MyKitchenHelper/base.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/inventory.css" %}"/>
{% endblock %}

<!-- TITLE -->

{% block title %}Inventory{% endblock %}

<!-- NAV BUTTONS -->

{% block nav %}
<ul>
	{% block navbuttons %}
	{% endblock %}
</ul>
{% endblock %}

{% block content %}

{% endblock %}


<!-- JS -->

{% block scriptlink %}
<script>
	activeNav("inventoryNav");
	var index_url = "{% url 'inventory:index' %}"
</script>
<script src="{% static "scripts/inventory.js" %}"></script>
<script>
attachGroupDisplayEventHandler()
updateAddDiv()
</script>
{% endblock %}

items/templates/inventory/detail.html
{% extends 'base_main.html' %}

	{% block header_text %}{{object|title}}{% endblock %}

	{% block body %}

	<div>
		<span>Items in stock: </span>
		<span>{{ object.stock }}</span>
	</div>

	{% endblock %}

items/templates/inventory/edit.html
{% extends 'inventory/base.html' %}

{% block title %}Edit Inventory{% endblock %}

{% block content %}

<form method="post" action="">
	
	{% csrf_token %}

	{{ formset.management_form }}

	<div id="objectseditlist">

		<div class="errors">
			{% if formset.total_error_count > 0 %}
				<p>Please Fix Errors!</p>
				{{ formset.non_form_errors }}
			{% endif %}
		</div>

		<table class="group">
		
		{% for form in formset %}
			
			{% if forloop.first %}
				<tr class="grouphead">
				{% for field in form %}
					<th>
					{% if field.label != "Id" %}
						{{field.label}}
					{% endif %}
					</th>
				{% endfor %}
				</tr>
			{% endif %}

			<tr>
			{% for field in form %}
				{% if field.label == "Stock" %}
				<td class="mcol">
				{% elif field.label == "Threshold" %}
				<td class="scol">
				{% elif field.label == "Category" %}
				<td class="lcol">
				{% elif field.label == "Name" %}
				<td class="xlcol">
				{% else %}
				<td>
				{% endif %}
				{{ field }}</td>
			{% endfor %}
			</tr>

			{% if form.errors %}
			<tr class="errorrow">
				{% for field in form %}
					<td>{{field.errors}}</td>
				{% endfor %}
			<tr>
			{% endif %}

		{% endfor %}
		</table>

		<nav>
			<ul class="contentnavbuttons">
				<li>
					<button type="submit" class="submit">
						<i class="fa fa-check-circle"></i>
					</button>						
				</li>
				<li id="canceladd">
					<a href="{% url 'inventory:index' %}">
						<i class="fa fa-times-circle"></i>
					</a>
				</li>
			</ul>
		</nav>

	</div>

</form>

{% endblock %}

items/templates/inventory/index.html
{% extends 'MyKitchenHelper/base_main.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/inventory.css" %}"/>
{% endblock %}

<!-- TITLE -->

{% block title %}Inventory{% endblock %}

<!-- NAV BUTTONS -->

{% block nav %}
<ul>
	<li id="groupby">
		<label>Group by: </label>
		<select id="InventoryGroupBy" autocomplete="off">
			<option value="name" selected="selected">name</option>
			<option value="category">category</option>
			<option value="status">status</option>
		</select>
	</li>
	<li id="additem"><i class="fa fa-plus-square"></i></li>
	<li id="edititems"><i class="fa fa-pencil-square"></i></li>
</ul>
{% endblock %}

{% block content %}
<div id="adddiv">
	{% include "inventory/index_adddiv.html" %}
</div>

<div id="inventorylist">
	{% include "inventory/index_results.html" %}
</div>
{% endblock %}


<!-- JS -->

{% block scriptlink %}
<script>
	activeNav("inventoryNav");
	var index_url = "{% url 'inventory:index' %}"
</script>
<script src="{% static "scripts/inventory.js" %}"></script>
<script>
attachGroupDisplayEventHandler()
updateAddDiv()
</script>
{% endblock %}

items/templates/inventory/index_adddiv.html
<form method="POST" id="addform">
	{% csrf_token %}
	{{ field.errors }}
	<table>
		<tr class="labels">
		{% for field in form %}
			<td>{{ field.label_tag }}</td>
		{% endfor %}
		</tr>
		<tr class="fields">
		{% for field in form %}
			<td>{{ field }}</td>
		{% endfor %}
		</tr>
	</table>
	<div id="errors"></div> <!-- errors go here -->
	<ul>
		<li id="submitadd">
			<i class="fa fa-check-circle"></i>
		</li>
		<li id="canceladd">
			<i class="fa fa-times-circle"></i>
		</li>
	</ul>

</form>

items/templates/inventory/index_backup.html
{% extends 'MyKitchenHelper/base.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/inventory.css" %}"/>
{% endblock %}

<!-- TITLE -->
{% block title %}Inventory{% endblock %}

<!-- NAV -->
{% block nav %}

<div id="groupby">
	<label>Group by: </label>
	<select id="GroupBy" autocomplete="off">
		<option value="name" selected="selected">name</option>
		<option value="category">category</option>
		<option value="status">status</option>
	</select>
</div>

<ul class="contentnavbuttons">
	<li id="addobject">
		<a href="{% url 'inventory:new' %}">
			<i class="fa fa-plus-square"></i>
		</a>
	</li>
	<li id="editobjects">
		<a href="{% url 'inventory:edit' %}">
			<i class="fa fa-pencil-square"></i>
		</a>
	</li>
</ul>
{% endblock %}

{% block content %}
	<div id="objectlist">
		{% include "inventory/index_results.html" %}
	</div>
{% endblock %}

{% block scriptlink %}
<script>
	activeNav("inventoryNav");
	var index_url = "{% url 'inventory:regroup' %}"
</script>
<script src="{% static "scripts/secondary.js" %}"></script>
<script>
	attachGroupDisplayEventHandler()
</script>

{% endblock %}

items/templates/inventory/index_results.html
{% if groupby == "name" %}
	{% regroup items by first_letter as grouped_list %}
{% elif groupby == "category" %}
	{% regroup items|dictsort:"category.name" by category as grouped_list %}
{% elif groupby == "status" %}
	{% regroup items|dictsort:"status.order" by status.status as grouped_list %}
{% endif %}

{% for group in grouped_list %}
<table class="group">
	<colgroup>
		<col span="1"></col>
		<col span="1"></col>
		<col span="1"></col>
	</colgroup>
	<tr class="grouphead">
		<th>
			<i class="groupdisplay fa fa-toggle-up"></i>
			{{ group.grouper|upper }}</th>
		<th>stock</th>
		<th>status</th>
		<th></th>
	</tr>
	{% for item in group.list %}
	<tr class="datarow rowshow">
		<td>{{ item }}</td>
		<td>{{ item.stock }}</td>
		<td>
		{% if item.status.status = "out" %}
		<i class="fa fa-times-circle"></i>
		{% elif item.status.status = "low" %}
		<i class="fa fa-exclamation-circle"></i>
		{% elif item.status.status = "na" %}
		<i class="fa fa-question-circle"></i>
		{% elif item.status.status = "ok" %}
		<i class="fa fa-check-circle"></i>
		{% endif %}
		</td>
		<td></td>
	</tr>
	{% endfor %}
</table>

{% endfor %}

items/templates/inventory/new.html
{% extends 'MyKitchenHelper/base.html' %}
	
{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/inventory.css" %}"/>
{% endblock %}

<!-- TITLE -->
{% block title %}Add New Item{% endblock %}

<!-- NAV -->
{% block nav %}
<div id="groupby">
	<label>Group by: </label>
	<select id="InventoryGroupBy" autocomplete="off">
		<option value="name" selected="selected">name</option>
		<option value="category">category</option>
		<option value="status">status</option>
	</select>
</div>
{% endblock %}

{% block precontent %}
	<div id="adddiv">
		<form id="additemform" method="post", action="">
			{% csrf_token %}
			{% for field in form %}
			<table class="fieldtable">
				<tr><td>{{ field.label }}</td></tr>
				<tr><td>{{ field }}</td></tr>
				{% if field.errors %}
				<tr><td class="errorlist">{{ field.errors }}</td></tr>
				{% endif %}
			</table>
			{% endfor %}
			<div class="clear"></div>
			<nav>
				<ul class="contentnavbuttons">
					<li>
						<button type="submit" class="submit">
							<i class="fa fa-check-circle"></i>
						</button>						
					</li>
					<li id="canceladditem">
						<a href="{% url 'inventory:index' %}">
							<i class="fa fa-times-circle"></i>
						</a>
					</li>
				</ul>
			</nav>

		</form>
	</div>
{% endblock %}


{% block content %}
	<div id="inventorylist">
		{% include "inventory/index_results.html" %}
	</div>
{% endblock %}

{% block scriptlink %}
<script>
	activeNav("inventoryNav");
	var index_url = "{% url 'inventory:regroup' %}"
</script>
<script src="{% static "scripts/inventory.js" %}"></script>
<script>
	attachGroupDisplayEventHandler()
</script>

{% endblock %}

recipes/templates/recipes/edit.html
{% extends 'inventory/base.html' %}

{% block title %}Edit Recipes{% endblock %}

{% block content %}

coming soon

{% endblock %}

recipes/templates/recipes/index.html
{% extends 'MyKitchenHelper/base_index.html' %}

{% block csslink %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/recipes.css" %}"/>
{% endblock %}

{% block title %}Recipe Book{% endblock %}

{% block nav %}
<div id="groupby">
	<label>Group by: </label>
	<select id="GroupBy" autocomplete="off">
		<option value="name" selected="selected">name</option>
	</select>
</div>

<ul class="contentnavbuttons">
	<li id="addobject">
		<a href="{% url 'recipes:new' %}">
			<i class="fa fa-plus-square"></i>
		</a>
	</li>
	<li id="editobjects">
		<a href="{% url 'recipes:edit' %}">
			<i class="fa fa-pencil-square"></i>
		</a>
	</li>
</ul>
{% endblock %}

{% block objectlist %}
	{% include "recipes/index_results.html" %}
{% endblock %}

{% block activenav %}"recipesNav"{% endblock %}

{% block indexurl %}
	"{% url 'recipes:regroup' %}"
{% endblock %}

recipes/templates/recipes/index_results.html
{% if groupby == "name" %}
	{% regroup recipes by first_letter as grouped_list %}
{% endif %}

{% for group in grouped_list %}
<table class="group">
	<colgroup>
		<col span="1"></col>
		<col span="1"></col>
		<col span="1"></col>
	</colgroup>
	<tr class="grouphead">
		<th>
			<i class="groupdisplay fa fa-toggle-up"></i>
			{{ group.grouper|upper }}</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	{% for item in group.list %}
	<tr class="datarow rowshow">
		<td>{{ item }}</td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	{% endfor %}
</table>

{% endfor %}

recipes/templates/recipes/new.html
{% extends 'recipes/index.html' %}
	
{% block title %}Add New Recipe{% endblock %}

{% block nav %}
<div id="groupby">
	<label>Group by: </label>
	<select id="GroupBy" autocomplete="off">
		<option value="name" selected="selected">name</option>
	</select>
</div>
{% endblock %}

{% block precontent %}
	<div id="adddiv">
		<form id="addform" method="post", action="">
			{% csrf_token %}
			{% for field in form %}
			<table class="fieldtable">
				<tr><td>{{ field.label }}</td></tr>
				<tr><td>{{ field }}</td></tr>
				{% if field.errors %}
				<tr><td class="errorlist">{{ field.errors }}</td></tr>
				{% endif %}
			</table>
			{% endfor %}
			<div class="clear"></div>
			<nav>
				<ul class="contentnavbuttons">
					<li>
						<button type="submit" class="submit">
							<i class="fa fa-check-circle"></i>
						</button>						
					</li>
					<li id="canceladd">
						<a href="{% url 'recipes:index' %}">
							<i class="fa fa-times-circle"></i>
						</a>
					</li>
				</ul>
			</nav>

		</form>
	</div>
{% endblock %}